### ISSUE TITLE
Malformed logo lines

### ISSUE THREAD

**Issue by alexjbuck** [spear-ai/logo#168]
The logo SVG uses cubic bezier paths when it is clearly a linear/straight-edge graphic design. There are several artifacts as a result of this, notably the bottom left edge which does not run flush/horizontal. 

Recommend creating logo with `lineto` or `polygon` SVG methods vice cubic bezier lines.

**Comment by psirenny** [comment]
THANK you for noticing! I pointed that out on Slack 😆.

**Comment by alexjbuck** [comment]
I've written a generator script that remakes the logo with straight lines vice curves. It looks nice. Its also parameterized in a way that makes generating variations of the logo easy.

**Comment by alexjbuck** [comment]
I can submit a PR that includes a yarn build step to add it to the src/assets/ folder and also update the other versions of the svg images.

**Comment by psirenny** [comment]
Would it work with our React logo too? It has some custom javascript logic in it: https://github.com/spear-ai/logo/blob/main/src/react/logo-icon.tsx#L12. We could copy/paste the updated paths in if not.

**Comment by alexjbuck** [comment]
I was thinking about forerunner logos based on our company logo and as I started looking closely at it, I noticed those curvy lines. HAD to fix it.

I can incorporate the logic from the generator into that React function component too.

**Comment by psirenny** [comment]
> I can incorporate the logic from the generator into that React function component too.

My only concern is that there would be a performance hit if that logic was executed at runtime.

**Comment by alexjbuck** [comment]
I can just copy the generated path then. The logic right now is just a string literal with some math to determine the coordinates. But you're right, it would recompute each time, vice just storing a good image in there. I'll leave the generator as a yarn script but I'll manually copy the new paths into the relevant files for performance.

**Comment by alexjbuck** [comment]
I don't have permission to push my new branch "fix/logo-shape"

**Comment by psirenny** [comment]
> I don't have permission to push my new branch "fix/logo-shape"

Try it now.
