### ISSUE TITLE
Create a Logo react component for dark mode

### ISSUE THREAD

**Issue by huntermc45** [spear-ai/logo#191]
Currently we export a Logo in light mode, but we also need an exportable component for dark mode.  Something like LogoDark and LogoLight

**Comment by psirenny** [comment]
Are you looking for it to be a React component or just a straight up SVG? If you want a React component then you can do something like this:

```tsx
import { Logo } from "@spear-ai/logo/react";

<Logo isDark />
```

If you want to reference a plain ol' SVG then you have a few options. If you're in JavaScript land and you have a bundler that import an SVG then this could work:

```ts
import logoDark from "@spear-ai/logo/assets/logo-dark.svg"; // Bundler configured to return a URL
// import LogoDark from "@spear-ai/logo/assets/logo-dark.svg"; // Bundler configured to return an SVG component


<img alt="Spear AI" src={logoDark.src} />
```

**Comment by psirenny** [comment]
The regular logo (not dark or light specific) does respond to the `prefers-color-scheme: dark` media query. Good to know just in case that's all that's needed. e.g. favicon.

**Comment by huntermc45** [comment]
Great thanks!  Closing now!
